name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Determine Foundry version
        id: version
        run: |
          version="${{ github.ref_name }}"
          version="${version%.*}"
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            Authentication patches for Foundry VTT ${{ steps.version.outputs.version }} and later.
          files: |
            patches.sh
